- cloudformation:
    region: "{{ nameofregion }}"
    stack_name: "{{ stackname }}"
    state: present
    template: roles/rdsdb/files/rdsdb.yaml
    template_parameters:
      vpcid: "{{ twotiervpc.stack_outputs.vpcid  }}"
      firstsubnetid: "{{ twotiervpc.stack_outputs.firstpublicsubnetid }}"
      secondsubnetid: "{{ twotiervpc.stack_outputs.secondpublicsubnetid }}"
      dbsgname: "{{ dbsgname }}"
      DBName: "{{ DBName }}"
      DBAllocatedStorage: "{{ DBAllocatedStorage }}"
      DBInstanceClass: "{{ DBInstanceClass }}"
      DBUser: "{{ DBUser }}"
      DBPassword: "{{ DBPassword }}"
  register: dbinstance
- debug:
    var: dbinstance
